export const skills = [
    // BOTTOM LEFT ARC - Web Dev
    {
        id: "html",
        label: "HTML",
        category: "web",
        x: 649,
        y: 800,
        unlocked: true,
        img: "/logos/html.png",
    },
    {
        id: "css",
        label: "CSS",
        category: "web",
        x: 475,
        y: 890,
        unlocked: true,
        img: "/logos/css.png",
    },
    {
        id: "react",
        label: "React",
        category: "web",
        x: 230,
        y: 1230,
        unlocked: true,
        img: "logos/react.png",
    },
    {
        id: "typescript",
        label: "TypeScript",
        category: "web",
        x: 250,
        y: 1100,
        unlocked: true,
        img: "logos/typescript.png",
    },
    {
        id: "js",
        label: "JavaScript",
        category: "web",
        x: 330,
        y: 990,
        unlocked: true,
        img: "logos/javascript.png",
    },
    {
        id: "node",
        label: "Node.js",
        category: "web",
        x: 340,
        y: 1350,
        unlocked: true,
        img: "logos/nodejs.png",
    },
    {
        id: "nextjs",
        label: "Next.js",
        category: "web",
        x: 335,
        y: 1235,
        unlocked: true,
        img: "logos/nextjs.png",
    },
    {
        id: "express",
        label: "Express",
        category: "web",
        x: 510,
        y: 1345,
        unlocked: true,
        img: "logos/express.png",
    },
    {
        id: "rest",
        label: "RESTful APIs",
        category: "web",
        x: 435,
        y: 1275,
        unlocked: true,
        img: "logos/restapi.png",
    },
    {
        id: "sql",
        label: "SQL",
        category: "web",
        x: 660,
        y: 1250,
        unlocked: true,
        img: "logos/sql.png",
    },
    {
        id: "mongo",
        label: "MongoDB",
        category: "web",
        x: 790,
        y: 1255,
        unlocked: true,
        img: "logos/mongodb.png",
    },
    {
        id: "docker",
        label: "Docker",
        category: "web",
        x: 775,
        y: 1150,
        unlocked: true,
        img: "logos/docker.png",
    },
    {
        id: "redis",
        label: "Redis",
        category: "web",
        x: 900,
        y: 1130,
        unlocked: true,
        img: "logos/redis.png",
    },


    // UPPER LEFT ARC - Academic Path (specific math courses)
    {
        id: "multicalc",
        label: "Multivariable Calculus",
        category: "academic",
        x: 510,
        y: 750,
        unlocked: true,
        img: "logos/multicalc.png",
    },
    {
        id: "linalg",
        label: "Linear Algebra",
        category: "academic",
        x: 370,
        y: 790,
        unlocked: true,
        img: "logos/linearalg.png"
    },
    {
        id: "probstats",
        label: "Probability & Statistics",
        category: "academic",
        x: 230,
        y: 785,
        unlocked: true,
        img: "logos/probstats.png",
    },
    {
        id: "r",
        label: "R Studio",
        category: "academic",
        x: 120,
        y: 690,
        unlocked: true,
        img: "logos/rstudio.png"
    },
    {
        id: "dataAnal",
        label: "Data Analysis",
        category: "academic",
        x: 105,
        y: 515,
        unlocked: true,
        img: "logos/dataanal.png"
    },
    {
        id: "python",
        label: "Python",
        category: "academic",
        x: 230,
        y: 310,
        unlocked: true,
        img: "logos/python.png"
    },
    {
        id: "pytorch",
        label: "PyTorch",
        category: "academic",
        x: 370,
        y: 270,
        unlocked: true,
        img: "logos/pytorch.png"
    },
    {
        id: "nn",
        label: "Neural Networks",
        category: "academic",
        x: 510,
        y: 230,
        unlocked: true,
        img: "logos/nn.jpg"
    },
    {
        id: "cogpsych",
        label: "Cognitive Psychology",
        category: "academic",
        x: 650,
        y: 200,
        unlocked: true,
        img: "logos/cogpsych.jpg"
    },

    // UPPER RIGHT ARC - Systems & Game Dev
    {
        id: "arch",
        label: "Computer Architecture",
        category: "systems",
        x: 930,
        y: 550,
        unlocked: true,
        img: "logos/comparch.png",
    },
    {
        id: "assembly",
        label: "Assembly",
        category: "systems",
        x: 1060,
        y: 500,
        unlocked: true,
        img: "logos/riscv.png"
    },
    {
        id: "c",
        label: "C",
        category: "systems",
        x: 1150,
        y: 390,
        unlocked: true,
        img: "logos/c.png",
    },
    {
        id: "cpp",
        label: "C++",
        category: "systems",
        x: 1148,
        y: 250,
        unlocked: true,
        img: "logos/cpp.png",
    },
    {
        id: "csharp",
        label: "C#",
        category: "systems",
        x: 1040,
        y: 140,
        unlocked: true,
        img: "logos/csharp.png",
    },
    {
        id: "godot",
        label: "Godot Engine",
        category: "systems",
        x: 900,
        y: 90,
        unlocked: true,
        img: "logos/godot.png",
    },
    {
        id: "unreal",
        label: "Unreal Engine 5",
        category: "systems",
        x: 760,
        y: 100,
        unlocked: true,
        img: "logos/unreal.png",
    },

    // CENTER HUB
    {
        id: "git",
        label: "Git/GitHub",
        category: "hub",
        x: 650,
        y: 445,
        unlocked: true,
        img: "/logos/github.png",
    },
    {
        id: "despatterns",
        label: "Design Patterns",
        category: "hub",
        x: 925,
        y: 275,
        unlocked: true,
        img: "logos/designpatterns.jpg",
    },

    // INNER RING - Foundation (120px spacing from hub)
    {
        id: "java",
        label: "Java",
        category: "foundation",
        x: 655,
        y: 610,
        unlocked: true,
        img: "/logos/java.png",
    },
    {
        id: "dsa",
        label: "Data Structures + Algorithms",
        category: "foundation",
        x: 792,
        y: 575,
        unlocked: true,
        img: "/logos/dsa.png",
    },
    {
        id: "oop",
        label: "Object-Oriented Programming",
        category: "foundation",
        x: 785,
        y: 445,
        unlocked: true,
        img: "/logos/oop.png",
    },
    {
        id: "discrete",
        label: "Discrete Mathematics",
        category: "foundation",
        x: 500,
        y: 545,
        unlocked: true,
        img: "/logos/discrete.png",
    },



    // DESIGN & TESTING BRANCH (right side)
    {
        id: "figma",
        label: "HCI/Figma",
        category: "design",
        x: 1150,
        y: 675,
        unlocked: true,
        img: "logos/figma.png",
    },
    {
        id: "testing",
        label: "Testing/QA",
        category: "web",
        x: 890,
        y: 990,
        unlocked: true,
        img: "logos/unittest.png",
    },

    // TO BE DETERMINED NODES (all around)
    {
        id: "tbd_web1",
        label: "Requires XP",
        category: "web",
        x: 735,
        y: 1375,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_web2",
        label: "Requires XP",
        category: "web",
        x: 1000,
        y: 1350,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_web3",
        label: "Requires XP",
        category: "web",
        x: 1150,
        y: 1249,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_web4",
        label: "Requires XP",
        category: "web",
        x: 1115,
        y: 975,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_web5",
        label: "Requires XP",
        category: "web",
        x: 1425,
        y: 1185,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_des1",
        label: "Requires XP",
        category: "design",
        x: 1275,
        y: 615,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_des2",
        label: "Requires XP",
        category: "design",
        x: 1272,
        y: 745,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_des3",
        label: "Requires XP",
        category: "design",
        x: 1472,
        y: 680,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_sys1",
        label: "Requires XP",
        category: "systems",
        x: 1272,
        y: 335,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_sys2",
        label: "Requires XP",
        category: "systems",
        x: 1172,
        y: 145,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_sys3",
        label: "Requires XP",
        category: "systems",
        x: 1345,
        y: 150,
        unlocked: false,
        img: "logos/question.png",
    },
    {
        id: "tbd_aca1",
        label: "Requires XP",
        category: "academic",
        x: 135,
        y: 150,
        unlocked: false,
        img: "logos/question.png",
    }

];